Telco Configure Account:
  extends:
    - .agent_tag
  stage: "Telco Account Setup"
  image: $DATAOPS_SNOWFLAKE_RUNNER_IMAGE
  variables:
    DATAOPS_SNOWSQL_USER: $DATAOPS_SNOWFLAKE_USER
    DATAOPS_SNOWSQL_ACCOUNT: $DATAOPS_SNOWFLAKE_ACCOUNT
    DATAOPS_SNOWSQL_ROLE: ACCOUNTADMIN
    DATAOPS_SNOWSQL_WAREHOUSE: ""
    DATAOPS_SNOWFLAKE_AUTH: KEY_PAIR
    DATAOPS_RUN_SQL: $CI_PROJECT_DIR/dataops/event/telco_configure_account.sql
  script:
    - bash $CI_PROJECT_DIR/pipelines/includes/local_includes/check_account_ready.sh
    - /dataops
  icon: ${SNOWFLAKE_ICON}

