Telco Deploy Applications:
  extends:
    - .agent_tag
  stage: "Telco Applications"
  needs:
    - job: "Initialise Pipeline"
    - job: "Telco Data Foundation"
  rules:
    - if: $EVENT_DEPLOY_TELCO == "true"
  image: $DATAOPS_SNOWFLAKE_RUNNER_IMAGE
  variables:
    DATAOPS_SNOWSQL_USER: $DATAOPS_SNOWFLAKE_USER
    DATAOPS_SNOWSQL_ACCOUNT: $DATAOPS_SNOWFLAKE_ACCOUNT
    DATAOPS_SNOWSQL_ROLE: ACCOUNTADMIN
    DATAOPS_SNOWSQL_WAREHOUSE: $EVENT_WAREHOUSE
    DATAOPS_SNOWFLAKE_AUTH: KEY_PAIR
    DATAOPS_RUN_SQL: $CI_PROJECT_DIR/dataops/event/telco_deploy_applications.sql
  script:
    - /dataops
  icon: ${SNOWFLAKE_ICON}

